# Generated by Django 5.0 on 2024-05-02 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trelloapp', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
